language: python

python:
  - "2.7"
  - "3.4"
  - "3.6"
  # command to install dependencies
install:
  - "pip install nose-cov"
  - "pip install tissue"
  - "pip install coveralls"
  - "pip install ."
  # command to run tests
script:
  - nosetests --with-cov --with-tissue --cov=pabot --cov-report term-missing
after_success:
  - coveralls
